### ISSUE TITLE
quetion about Fig.4(b) of page5

### ISSUE THREAD

**Issue by sunjieemm** [kiva12138/MITRL#1]
Hi,
why the second part in GIMA is Z_{m_2 \to m_1} instead of  Z_{m_1 \to m_2}?

**Comment by kiva12138** [comment]
Oh! Thanks for the careful reading. We are very sorry for the wrong spelling. The second part should be Z{m1 to m2}. 
And as you can see, the repo is still too humble, we are trying to make it better.

Thanks again for pointing out the issue.

**Comment by sunjieemm** [comment]
all right, thanks for disabusing my confusion!
