### ISSUE TITLE
数据集MOSI,POM,IEMOCAP

### ISSUE THREAD

**Issue by xiajili** [kiva12138/MITRL#2]
可以提供一下实验所用的数据集吗？

**Comment by kiva12138** [comment]
论文中所采用的数据都来自于另一篇论文提供的代码数据。
论文为Context-aware Interactive Attention for Multi-modal Sentiment and Emotion Analysis
具体链接为https://drive.google.com/drive/folders/1IVgdjfRGSqnai45ksot7UZ5C-1xJBBWZ?usp=sharing
已经在markdown文件中说明。
感谢指出。

**Comment by xiajili** [comment]
非常感谢！
另外，在TrainSimilarityWithLoss.py文件中，对于from SAM import SAM有些疑惑，这句代码总是报错，SAM是自定义的包还是系统包？无论是conda和pip都无法安装到它。我的环境是python3.6.
在此感谢您的答疑！

**Comment by kiva12138** [comment]
感谢指出错误，SAM是一个自定义的优化器，是我从前人代码中学习得到来的，但是实际并没有使用到SAM优化器。
我会在代码中改正，如果你需要的话，请邮件发送至sunhaoxx@zju.edu.cn。我会将代码发与你。
