### ISSUE TITLE
Error funtion: make_weights_for_balanced_classes

### ISSUE THREAD

**Issue by JackAILab** [kiva12138/MITRL#3]
Dear author,

I find that the function make_weights_for_balanced_classes you used in Utils.py seems to be wrong.

![image](https://user-images.githubusercontent.com/112920087/233600933-077a9fa1-2bd5-4b95-9044-c097090e2ecc.png)

the count will get zero value
![image](https://user-images.githubusercontent.com/112920087/233601772-3ee4625f-31ad-4206-ac6e-b7d9bba80b2f.png)

how to correctly solve this problem? I am looking forward to your early reply! Thank you a lot!

**Comment by kiva12138** [comment]
I have fixed this bug. In line 227, a non-zero judgement should be appened.
